### ISSUE TITLE
Product synchronization with Google Shopping completed

### ISSUE THREAD

**Issue by sabaqahmad** [5mehulhelp5/MagentoExtensions#2]
Hi,

When i go to catalog > Google Content API v2 > manage Items, choose some items from the "Available Products", select "Add to Google Content" from Actions dropdown and click "Submit", then the Submit button just faded with some processing icon and after few seconds, the page get refreshed but the chosen items have not added to the "Google Content Items".

Please advise!

**Comment by 5mehulhelp5** [comment]
There are several possibility for this kind of error.
1>Please check your magento compiler if it's enable then plese disable That.
2>Please check your magento extension setting and please check your magento notification wher you can see all error which you got will adding to google so please check that.

Also you can add me into the skype for more detail. 
skype id: mehul.chaudhari.

Thank you
