### ISSUE TITLE
Fatal Error?

### ISSUE THREAD

**Issue by comingloud** [5mehulhelp5/MagentoExtensions#3]
On GoogleshoppingApi V2

Fatal error: Call to a member function getFrontend() on a non-object in D:\www\www689\ausweisshop\app\code\community\Weboffice\GoogleShoppingApi\Model\Attribute\GoogleProductCategory.php on line 31

**Comment by 5mehulhelp5** [comment]
Hello
Thank you For your bug report But can you tell me your magento version?
Thank you 
Have a nice Day :)

**Comment by picturesque** [comment]
1.9.2.1

Michael Davidson

Picturesque

603-539-9090

**Comment by 5mehulhelp5** [comment]
Hi
Thank you for replay 
can you check "Google Shopping Category" this attribute in your magento 
Is that attribute available or not?
1>catalog > manage attributes > check this attribute (Google Shopping Category)
If that attribute is available then please check that attribute is assigned in all attribute sets or not?
1>catalog > manage attribute sets > open all attribute set and then check it's assigned or not.

Thank you and please let me know if you still have any problem.
Have a nice day :)

**Comment by picturesque** [comment]
I think issues crossed wires here. This original item wasn't my issue.

Michael Davidson
Picturesque
http://www.picturesqueweb.com

**Comment by 5mehulhelp5** [comment]
Yes sure @picturesque 
Let me know your issue.
Thank you.
